#!/usr/bin/env python3
"""Plot Hermite scaling curves versus P for d_sweep_hermite experiments.

This script mirrors the P-scan analysis workflow used for the erf experiments,
but replaces the theory branch with the Hermite continuation solver from
lib/hermite_activation_solvers.py and replaces the empirical quantities with
projection variances of the second hidden layer preactivations onto He1/He3.

For each run it computes:
  - H11_emp: variance of <h_k(x), He1(x_0)> across neuron/seed index
  - H33_emp: variance of <h_k(x), He3(x_0)> across neuron/seed index
  - lambda_sigma_emp: top eigenvalue of the readin covariance (W0)

Theoretical curves are generated by solving the Hermite fixed-point system
over a log-P interval covering the observed experiments.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import re
import sys
import traceback
from collections import defaultdict
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Tuple

import matplotlib.pyplot as plt
import numpy as np
import torch

sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "lib"))
from FCN3Network import FCN3NetworkActivationGeneric
from hermite_activation_solvers import solve_pac_eos

plt.rcParams.update(
    {
        "font.size": 16,
        "axes.labelsize": 18,
        "axes.titlesize": 20,
        "legend.fontsize": 14,
        "xtick.labelsize": 15,
        "ytick.labelsize": 15,
        "figure.dpi": 150,
    }
)

DEVICE_DEFAULT = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
RESULTS_DIR_DEFAULT = Path(__file__).resolve().parent / "results"
CACHE_DIR_DEFAULT = RESULTS_DIR_DEFAULT / "analysis_cache"


def safe_float(value):
    try:
        return float(value)
    except Exception:
        return float("nan")


def parse_run_config(run_dir: Path) -> Dict[str, float]:
    cfg_path = run_dir / "config.json"
    cfg: Dict[str, float] = {}
    if cfg_path.exists():
        try:
            with open(cfg_path, "r") as f:
                cfg = json.load(f)
        except Exception:
            cfg = {}

    dirname_match = re.match(
        r"d(?P<d>\d+)_P(?P<P>\d+)_N(?P<N>\d+)_chi(?P<chi>[-+]?\d*\.?\d+)_kappa(?P<kappa>[-+]?\d*\.?\d+)",
        run_dir.parent.name,
    )
    if dirname_match:
        cfg.setdefault("d", int(dirname_match.group("d")))
        cfg.setdefault("P", int(dirname_match.group("P")))
        cfg.setdefault("N", int(dirname_match.group("N")))
        cfg.setdefault("chi", float(dirname_match.group("chi")))
        cfg.setdefault("kappa", float(dirname_match.group("kappa")))

    seed_match = re.search(r"seed(\d+)", run_dir.name)
    if seed_match:
        cfg.setdefault("seed", int(seed_match.group(1)))

    cfg.setdefault("eps", cfg.get("epsilon", 0.03))
    cfg.setdefault("activation", "hermite3")
    return cfg


def find_run_dirs(results_dir: Path, ignore_seeds: Iterable[int]) -> List[Path]:
    ignored = set(ignore_seeds)
    run_dirs: List[Path] = []
    for run_dir in sorted(results_dir.glob("d*/*seed*")):
        if not run_dir.is_dir():
            continue
        seed_match = re.search(r"seed(\d+)", run_dir.name)
        if seed_match and int(seed_match.group(1)) in ignored:
            continue
        if (run_dir / "config.json").exists() and ((run_dir / "model_final.pt").exists() or (run_dir / "model.pt").exists()):
            run_dirs.append(run_dir)

    return run_dirs


def load_model(run_dir: Path, cfg: Dict[str, float], device: torch.device) -> Optional[FCN3NetworkActivationGeneric]:
    model_path = run_dir / "model_final.pt"
    if not model_path.exists():
        model_path = run_dir / "model.pt"
    if not model_path.exists():
        return None

    state_dict = torch.load(model_path, map_location="cpu")
    if isinstance(state_dict, dict) and "model_state_dict" in state_dict:
        state_dict = state_dict["model_state_dict"]
    if len(state_dict["W0"].shape) == 4:
        state_dict["W0"] = state_dict["W0"].squeeze(0)
        state_dict["W1"] = state_dict["W1"].squeeze(0)
        state_dict["A"] = state_dict["A"].squeeze(0)

    d = int(cfg["d"])
    P = int(cfg["P"])
    N = int(cfg["N"])
    chi = float(cfg["chi"])
    ens = int(state_dict["W0"].shape[0])

    model = FCN3NetworkActivationGeneric(
        d=d,
        n1=N,
        n2=N,
        P=P,
        ens=ens,
        activation="hermite3",
        weight_initialization_variance=(1.0 / d, 1.0 / N, 1.0 / (N * chi)),
    ).to(device)
    model.load_state_dict(state_dict, strict=False)
    model.eval()
    return model


def make_group_key(cfg: Dict[str, float]) -> Tuple[float, float, float, float, float]:
    return (
        safe_float(cfg.get("d")),
        safe_float(cfg.get("N")),
        safe_float(cfg.get("chi")),
        safe_float(cfg.get("kappa")),
        safe_float(cfg.get("eps", cfg.get("epsilon", 0.074))),
    )


def group_label(cfg: Dict[str, float]) -> str:
    return (
        f"d={int(cfg['d'])}, N={int(cfg['N'])}, "
        f"chi={safe_float(cfg['chi']):.3g}, kappa={safe_float(cfg['kappa']):.3g}, eps={safe_float(cfg.get('eps', 0.03)):.3g}"
    )


def cache_key(prefix: str, payload: Dict[str, float]) -> str:
    text = json.dumps(payload, sort_keys=True, default=float)
    return f"{prefix}_{hashlib.md5(text.encode()).hexdigest()}"


def load_cache(cache_dir: Path, key: str) -> Optional[Dict[str, object]]:
    path = cache_dir / f"{key}.json"
    if not path.exists():
        return None
    try:
        with open(path, "r") as f:
            return json.load(f)
    except Exception:
        return None


def save_cache(cache_dir: Path, key: str, data: Dict[str, object]) -> None:
    cache_dir.mkdir(parents=True, exist_ok=True)
    path = cache_dir / f"{key}.json"
    with open(path, "w") as f:
        json.dump(data, f, indent=2)


def compute_readin_lambda_sigma(model: FCN3NetworkActivationGeneric) -> float:
    with torch.no_grad():
        w0 = model.W0.detach().to(torch.float32)
        w0_flat = w0.reshape(-1, w0.shape[-1])
        cov = (w0_flat.t() @ w0_flat) / max(w0_flat.shape[0], 1)
        eigvals = torch.linalg.eigvalsh(cov)
        return float(eigvals.max().item())


def compute_projection_variances(
    model: FCN3NetworkActivationGeneric,
    d: int,
    total_samples: int,
    batch_size: int,
    device: torch.device,
    seed: int,
) -> Dict[str, float]:
    """Estimate variances of the He1/He3 projection coefficients."""

    torch.manual_seed(seed)
    n_features = model.ensembles * model.n2
    accum = torch.zeros((2, n_features), dtype=torch.float32, device=device)
    seen = 0
    sqrt6 = math.sqrt(6.0)

    with torch.no_grad():
        while seen < total_samples:
            bs = min(batch_size, total_samples - seen)
            x = torch.randn(bs, d, device=device)
            h1 = model.h1_preactivation(x).reshape(bs, -1)
            x0 = x[:, 0]
            he3 = (x0**3 - 3.0 * x0) / sqrt6
            accum[0].add_(torch.matmul(x0, h1))
            accum[1].add_(torch.matmul(he3, h1))
            seen += bs

    coeffs = (accum / float(total_samples)).view(2, model.ensembles, model.n2)
    h11_emp = float(coeffs[0].var(unbiased=False).item())
    h33_emp = float(coeffs[1].var(unbiased=False).item())
    return {
        "H11_emp": h11_emp,
        "H33_emp": h33_emp,
    }


def load_or_compute_empirical(
    run_dir: Path,
    cfg: Dict[str, float],
    device: torch.device,
    cache_dir: Path,
    total_samples: int,
    batch_size: int,
    force: bool,
) -> Optional[Dict[str, float]]:
    key = cache_key(
        "emp",
        {
            "run_dir": str(run_dir),
            "d": cfg.get("d"),
            "P": cfg.get("P"),
            "N": cfg.get("N"),
            "chi": cfg.get("chi"),
            "kappa": cfg.get("kappa"),
            "eps": cfg.get("eps", 0.03),
            "seed": cfg.get("seed"),
            "samples": total_samples,
            "batch_size": batch_size,
            "activation": cfg.get("activation", "hermite3"),
        },
    )
    if not force:
        cached = load_cache(cache_dir, key)
        if cached is not None:
            return {
                "H11_emp": safe_float(cached.get("H11_emp")),
                "H33_emp": safe_float(cached.get("H33_emp")),
                "lambda_sigma_emp": safe_float(cached.get("lambda_sigma_emp")),
            }

    model = load_model(run_dir, cfg, device)
    if model is None:
        return None

    try:
        proj = compute_projection_variances(
            model=model,
            d=int(cfg["d"]),
            total_samples=total_samples,
            batch_size=batch_size,
            device=device,
            seed=int(cfg.get("seed", 0)),
        )
        proj["lambda_sigma_emp"] = compute_readin_lambda_sigma(model)
        save_cache(cache_dir, key, proj)
        return proj
    except Exception as exc:
        print(f"  Warning: failed to compute empirical stats for {run_dir}: {exc}")
        traceback.print_exc()
        return None


def theory_cache_payload(cfg: Dict[str, float], q_start: float, q_end: float, ds: float, max_steps: int) -> Dict[str, float]:
    return {
        "d": cfg.get("d"),
        "N": cfg.get("N"),
        "chi": cfg.get("chi"),
        "kappa": cfg.get("kappa"),
        "eps": cfg.get("eps", 0.03),
        "q_start": q_start,
        "q_end": q_end,
        "ds": ds,
        "max_steps": max_steps,
    }


def load_or_compute_theory_curve(
    cfg: Dict[str, float],
    q_start: float,
    q_end: float,
    ds: float,
    max_steps: int,
    cache_dir: Path,
    force: bool,
) -> Optional[Dict[str, List[float]]]:
    print(cfg)
    key = cache_key("theory", theory_cache_payload(cfg, q_start, q_end, ds, max_steps))
    if not force:
        cached = load_cache(cache_dir, key)
        if cached is not None:
            return cached
    import math
    try:
        P_curve, H11_curve, H33_curve, lambda_sigma_curve = solve_pac_eos(
            d=int(cfg["d"]),
            N1=200,#int(cfg["N"]),
            N2=200,#int(cfg["N"]),
            chi=200,#float(cfg["chi"]),
            kappa=0.1,#float(cfg["kappa"]),
            epsilon=float(0.074), #cfg.get("eps", 0.074)),
            q_start=float(math.log10(1.0)),
            q_end=float(math.log10(1000.0)),
            ds_nominal=float(0.15),
            max_steps=int(1000),
        )
    except Exception as exc:
        print(f"  Warning: Hermite theory solver failed for {group_label(cfg)}: {exc}")
        traceback.print_exc()
        return None

    theory = {
        "P": [float(x) for x in P_curve.tolist()],
        "H11": [float(x) for x in H11_curve.tolist()],
        "H33": [float(x) for x in H33_curve.tolist()],
        "lambda_sigma": [float(x) for x in lambda_sigma_curve.tolist()],
    }
    save_cache(cache_dir, key, theory)
    return theory


def sem(values: List[float]) -> float:
    finite = [v for v in values if np.isfinite(v)]
    if len(finite) <= 1:
        return 0.0
    return float(np.std(finite, ddof=1) / np.sqrt(len(finite)))


def build_groups(rows: List[Dict[str, float]]) -> Dict[Tuple[float, float, float, float, float], List[Dict[str, float]]]:
    groups: Dict[Tuple[float, float, float, float, float], List[Dict[str, float]]] = defaultdict(list)
    for row in rows:
        groups[make_group_key(row)].append(row)
    return groups


def group_statistics(rows: List[Dict[str, float]], metric: str) -> Tuple[List[float], List[float], List[float]]:
    p_to_vals: Dict[float, List[float]] = defaultdict(list)
    for row in rows:
        p_to_vals[safe_float(row["P"])].append(safe_float(row[metric]))
    ps = sorted(p_to_vals.keys())
    means = [float(np.mean(p_to_vals[p])) for p in ps]
    errs = [sem(p_to_vals[p]) for p in ps]
    return ps, means, errs


def plot_metric_panel(
    ax,
    groups: Dict[Tuple[float, float, float, float, float], List[Dict[str, float]]],
    metric: str,
    title: str,
    ylabel: str,
    colors: List,
    theory_curves: Dict[Tuple[float, float, float, float, float], Dict[str, List[float]]],
):
    x_values: List[float] = []
    y_values: List[float] = []

    for idx, (key, rows) in enumerate(groups.items()):
        rows = sorted(rows, key=lambda r: safe_float(r["P"]))
        ps, means, errs = group_statistics(rows, metric)
        color = colors[idx % len(colors)]
        label = group_label(rows[0]) if idx == 0 else group_label(rows[0])
        ax.errorbar(ps, means, yerr=errs, fmt="o-", color=color, capsize=4, alpha=0.85, linewidth=2.2, markersize=5, label=label)

        x_values.extend(ps)
        y_values.extend(v for v in means if np.isfinite(v) and v > 0)
        y_values.extend(v for v in (m - e for m, e in zip(means, errs)) if np.isfinite(v) and v > 0)
        y_values.extend(v for v in (m + e for m, e in zip(means, errs)) if np.isfinite(v) and v > 0)

        theory = theory_curves.get(key)
        if theory:
            metric_key = {
                "H11_emp": "H11",
                "H33_emp": "H33",
                "lambda_sigma_emp": "lambda_sigma",
            }[metric]
            ax.plot(
                theory["P"],
                theory[metric_key],
                linestyle="--",
                linewidth=2.5,
                color=color,
                alpha=0.95,
            )
            x_values.extend(theory["P"])
            y_values.extend(v for v in theory[metric_key] if np.isfinite(v) and v > 0)

    ax.set_xscale("log")
    # ax.set_yscale("log")
    ax.set_xlabel("P")
    ax.set_ylabel(ylabel)
    ax.set_title(title)
    ax.grid(True, alpha=0.3)

    if x_values:
        x_min = min(x_values)
        x_max = max(x_values)
        x_pad = max((x_max - x_min) * 0.05, x_min * 0.08)
        # ax.set_xlim(left=max(x_min - x_pad, np.finfo(float).tiny), right=x_max + x_pad)

    if y_values:
        y_min = min(y_values)
        y_max = max(y_values)
        # ax.set_ylim(bottom=max(y_min * 0.8, np.finfo(float).tiny), top=y_max * 1.2)


def main():
    parser = argparse.ArgumentParser(description="Plot Hermite scaling curves versus P.")
    parser.add_argument("--results-dir", type=Path, default=RESULTS_DIR_DEFAULT, help="Root directory containing d_sweep_hermite outputs")
    parser.add_argument("--out-dir", type=Path, default=None, help="Directory where plots and caches will be written")
    parser.add_argument("--device", type=str, default=None, help="PyTorch device, e.g. cuda:0 or cpu")
    parser.add_argument("--ignore-seeds", type=int, nargs="*", default=[], help="Seed ids to skip")
    parser.add_argument("--force", action="store_true", help="Recompute cached empirical and theory results")
    parser.add_argument("--total-samples", type=int, default=500_000, help="Monte Carlo samples used for projection variance estimates")
    parser.add_argument("--batch-size", type=int, default=50_000, help="Batch size for projection variance estimates")
    parser.add_argument("--solver-ds", type=float, default=0.15, help="Nominal arclength step for the Hermite solver")
    parser.add_argument("--solver-max-steps", type=int, default=1000, help="Maximum continuation steps for the Hermite solver")
    parser.add_argument("--solver-padding", type=float, default=0.08, help="Padding added to log10(P) range before solving theory")
    args = parser.parse_args()

    results_dir = args.results_dir
    out_dir = args.out_dir or (results_dir / "hermite_scaling_plots")
    cache_dir = out_dir / "analysis_cache"
    out_dir.mkdir(parents=True, exist_ok=True)
    cache_dir.mkdir(parents=True, exist_ok=True)

    device = torch.device(args.device) if args.device else DEVICE_DEFAULT
    run_dirs = find_run_dirs(results_dir, args.ignore_seeds)
    if not run_dirs:
        print(f"No Hermite runs found under {results_dir}")
        return

    rows: List[Dict[str, float]] = []
    for run_dir in run_dirs:
        cfg = parse_run_config(run_dir)
        if any(key not in cfg for key in ("d", "P", "N", "chi", "kappa")):
            print(f"Skipping {run_dir}: missing run parameters")
            continue

        emp = load_or_compute_empirical(
            run_dir=run_dir,
            cfg=cfg,
            device=device,
            cache_dir=cache_dir,
            total_samples=args.total_samples,
            batch_size=args.batch_size,
            force=args.force,
        )
        if emp is None:
            continue

        row = {
            **cfg,
            **emp,
            "run_dir": str(run_dir),
        }
        rows.append(row)

    if not rows:
        print("No empirical Hermite measurements were produced.")
        return

    groups = build_groups(rows)
    theory_curves: Dict[Tuple[float, float, float, float, float], Dict[str, List[float]]] = {}
    for key, group_rows in groups.items():
        group_cfg = group_rows[0]
        ps = [safe_float(r["P"]) for r in group_rows if np.isfinite(safe_float(r["P"]))]
        if not ps:
            continue
        q_start = math.log10(1.0) # math.log10(min(ps)) - args.solver_padding
        q_end = math.log10(1000) #+ args.solver_padding
        theory = load_or_compute_theory_curve(
            cfg=group_cfg,
            q_start=q_start,
            q_end=q_end,
            ds=args.solver_ds,
            max_steps=args.solver_max_steps,
            cache_dir=cache_dir,
            force=args.force,
        )
        if theory is not None:
            theory_curves[key] = theory

    unique_colors = plt.colormaps["viridis"](np.linspace(0.15, 0.9, max(len(groups), 1)))

    fig, axes = plt.subplots(1, 3, figsize=(19, 6), sharex=True)
    plot_metric_panel(
        axes[0],
        groups,
        "H11_emp",
        r"Hermite $H_{11}$ scaling",
        r"$H_{11}$",
        list(unique_colors),
        theory_curves,
    )
    plot_metric_panel(
        axes[1],
        groups,
        "H33_emp",
        r"Hermite $H_{33}$ scaling",
        r"$H_{33}$",
        list(unique_colors),
        theory_curves,
    )
    plot_metric_panel(
        axes[2],
        groups,
        "lambda_sigma_emp",
        r"Hermite $\lambda_\sigma$ scaling",
        r"$\lambda_\sigma$",
        list(unique_colors),
        theory_curves,
    )

    handles, labels = axes[0].get_legend_handles_labels()
    if handles:
        fig.legend(handles, labels, loc="upper center", ncol=min(len(labels), 3), framealpha=0.95)

    fig.suptitle(r"Hermite scaling versus $P$: empirical projection variances and solver curves", y=1.04)
    fig.tight_layout()
    out_path = out_dir / "hermite_scaling_P.png"
    fig.savefig(out_path, dpi=300, bbox_inches="tight")
    plt.close(fig)
    print(f"Saved Hermite scaling plot to {out_path}")


if __name__ == "__main__":
    main()