# Default configuration for EnsembleManager
self_destruct: false
cash_freak: 2000
init_seed: 222

# Data and Model Dimensions
input_dimension: 50
hidden_width1: 200
hidden_width2: 200
num_data_points: 400
batch_size: 400

# Training Parameters
num_epochs: 100000
num_ensembles: 20 # Number of models per dataset
num_datasets: 3

# Model Builder and Callbacks
# Set to 'default' to use the EnsembleManager's internal defaults.
# Otherwise, provide a string reference to a custom function or class if your system supports it.
# For example, if you have a function `my_custom_teacher_builder` defined elsewhere,
# you might use `teacher_builder: 'my_custom_teacher_builder'`.
# In this specific Python script, 'default' triggers the internal _default_fcn3_model_builder, etc.
model_type: 'fcn3'
description: 'Training a bunch of FCN3s'

